name: 'Jira bulk update issues'
description: 'Action to update a specified field for all found Jira issues'
branding:
  icon: "cloud"
  color: "purple"

inputs:
  domain:
    description: 'Domain name of the Jira cloud instance (e.g. your-domain.atlassian.net)'
    required: true
  username:
    description: 'Jira Username'
    required: true
  password:
    description: 'Jira Personal Access Token'
    required: true
  jql:
    description: 'The JQL query to identify the issues to update'
    required: true
  fieldName:
    description: 'The name of the field to update (careful with custom fields)'
    required: true
  fieldValue:
    description: 'The value to set the field to'
    required: true
runs:
  using: 'node20'
  main: 'index.js'
